name: Publish

on:
    push:
        branches: [main]

permissions:
    contents: write

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout with write perms
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  persist-credentials: true

            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20.x
                  registry-url: https://registry.npmjs.org/

            - run: yarn install --frozen-lockfile

            - name: Publish to npm via Changesets
              uses: changesets/action@v1
              with:
                  publish: yarn release
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
