name: Publish

on:
    pull_request:
        types: [closed]
        branches: [main]

permissions:
    contents: write

jobs:
    publish:
        if: >
            github.event.pull_request.merged == true &&
            startsWith(github.event.pull_request.head.ref, 'changeset-release')
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  persist-credentials: true

            - uses: actions/setup-node@v4
              with:
                  node-version: 20.x
                  registry-url: https://registry.npmjs.org/

            - run: yarn install --frozen-lockfile

            - name: Publish via Changesets
              uses: changesets/action@v1
              with:
                  publish: yarn release
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
