name: “Create Release PR”

on:
    workflow_run:
        workflows: ['CI']
        branches: [main]
        types: [completed]

jobs:
    version:
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20.x
            - run: yarn install --frozen-lockfile
            - name: Create version bump PR only
              uses: changesets/action@v1
              with:
                  # don’t publish yet, only open the “Version Packages” PR
                  create-release-pr-only: true
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
