name: Create Release PR
on:
    workflow_run:
        workflows: ['CI']
        branches: [main]
        types: [completed]

permissions:
    contents: write
    pull-requests: write

jobs:
    version:
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout + prep for push
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  ref: main
                  persist-credentials: true

            - name: Install deps
              run: yarn install --frozen-lockfile

            - name: Create version bump PR
              uses: changesets/action@v1
              with:
                  version: yarn changeset version
                  commit: true
                  commitMode: 'git-cli'
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
